#pragma once

#include "common/enums.h"
#include "common/types.h"
#include "model/order.h"

namespace matching_engine::model {

// Order-facing event generated by engine.
// Trade is modeled separately and is NOT mixed into EventType.
struct Event {
    EventType type {EventType::Ack};

    SymbolId symbol_id {kInvalidSymbolId};

    // Main order id this event is about.
    OrderId order_id {kInvalidOrderId};

    // Optional related order id.
    // For example, on replace ack this can be old/new depending on usage policy.
    OrderId related_order_id {kInvalidOrderId};

    Price price {kInvalidPrice};
    Quantity quantity {kInvalidQuantity};
    Quantity leaves_quantity {kInvalidQuantity};

    RejectReason reason {RejectReason::None};

    Sequence sequence {kInvalidSequence};
    Timestamp timestamp {kInvalidTimestamp};

    [[nodiscard]] bool is_reject() const noexcept {
        return type == EventType::Reject
            || type == EventType::CancelReject
            || type == EventType::ReplaceReject;
    }

    [[nodiscard]] bool is_ack() const noexcept {
        return type == EventType::Ack
            || type == EventType::CancelAck
            || type == EventType::ReplaceAck;
    }

    static Event make_ack(const Order& order) noexcept {
        Event e;
        e.type = EventType::Ack;
        e.symbol_id = order.symbol_id;
        e.order_id = order.order_id;
        e.price = order.price;
        e.quantity = order.quantity;
        e.leaves_quantity = order.leaves_quantity;
        e.sequence = order.sequence;
        e.timestamp = order.updated_at;
        return e;
    }

    static Event make_reject(OrderId order_id,
                             SymbolId symbol_id,
                             RejectReason reason,
                             Sequence sequence,
                             Timestamp timestamp) noexcept {
        Event e;
        e.type = EventType::Reject;
        e.symbol_id = symbol_id;
        e.order_id = order_id;
        e.reason = reason;
        e.sequence = sequence;
        e.timestamp = timestamp;
        return e;
    }

    static Event make_partial_fill(const Order& order) noexcept {
        Event e;
        e.type = EventType::PartialFill;
        e.symbol_id = order.symbol_id;
        e.order_id = order.order_id;
        e.price = order.price;
        e.quantity = order.filled_quantity();
        e.leaves_quantity = order.leaves_quantity;
        e.sequence = order.sequence;
        e.timestamp = order.updated_at;
        return e;
    }

    static Event make_fill(const Order& order) noexcept {
        Event e;
        e.type = EventType::Fill;
        e.symbol_id = order.symbol_id;
        e.order_id = order.order_id;
        e.price = order.price;
        e.quantity = order.quantity;
        e.leaves_quantity = 0;
        e.sequence = order.sequence;
        e.timestamp = order.updated_at;
        return e;
    }

    static Event make_cancel_ack(const Order& order,
                                 Sequence sequence,
                                 Timestamp timestamp) noexcept {
        Event e;
        e.type = EventType::CancelAck;
        e.symbol_id = order.symbol_id;
        e.order_id = order.order_id;
        e.price = order.price;
        e.quantity = order.quantity;
        e.leaves_quantity = order.leaves_quantity;
        e.sequence = sequence;
        e.timestamp = timestamp;
        return e;
    }

    static Event make_cancel_reject(OrderId order_id,
                                    SymbolId symbol_id,
                                    RejectReason reason,
                                    Sequence sequence,
                                    Timestamp timestamp) noexcept {
        Event e;
        e.type = EventType::CancelReject;
        e.symbol_id = symbol_id;
        e.order_id = order_id;
        e.reason = reason;
        e.sequence = sequence;
        e.timestamp = timestamp;
        return e;
    }

    static Event make_replace_ack(OrderId old_order_id,
                                  const Order& new_order,
                                  Sequence sequence,
                                  Timestamp timestamp) noexcept {
        Event e;
        e.type = EventType::ReplaceAck;
        e.symbol_id = new_order.symbol_id;
        e.order_id = new_order.order_id;
        e.related_order_id = old_order_id;
        e.price = new_order.price;
        e.quantity = new_order.quantity;
        e.leaves_quantity = new_order.leaves_quantity;
        e.sequence = sequence;
        e.timestamp = timestamp;
        return e;
    }

    static Event make_replace_reject(OrderId old_order_id,
                                     SymbolId symbol_id,
                                     RejectReason reason,
                                     Sequence sequence,
                                     Timestamp timestamp) noexcept {
        Event e;
        e.type = EventType::ReplaceReject;
        e.symbol_id = symbol_id;
        e.order_id = old_order_id;
        e.reason = reason;
        e.sequence = sequence;
        e.timestamp = timestamp;
        return e;
    }
};

} // namespace matching_engine::model