#pragma once

#include "common/types.h"

namespace matching_engine::model {

// A trade is an execution fact generated by matching.
struct Trade {
    TradeId trade_id {kInvalidTradeId};
    SymbolId symbol_id {kInvalidSymbolId};

    OrderId buy_order_id {kInvalidOrderId};
    OrderId sell_order_id {kInvalidOrderId};

    Price trade_price {kInvalidPrice};
    Quantity trade_quantity {kInvalidQuantity};

    Sequence sequence {kInvalidSequence};
    Timestamp timestamp {kInvalidTimestamp};

    [[nodiscard]] bool valid() const noexcept {
        return trade_id != kInvalidTradeId
            && symbol_id != kInvalidSymbolId
            && buy_order_id != kInvalidOrderId
            && sell_order_id != kInvalidOrderId
            && trade_price > 0
            && trade_quantity > 0;
    }
};

} // namespace matching_engine::model